version: "3"
services:
  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www
    ports:
      - 3000:3000

  nginx:
    image: nginx
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./docker/db/data:/var/lib/postgresql
    ports:
      - 5433:5432
